import json
from django.shortcuts import render
from django.http import JsonResponse

PRODUCTS_DATA = [
    {
        "id": 1,
        "name": "Dutch Red Velvet Roses",
        "category": "roses",
        "flower_type": "Roses",
        "color": "Red",
        "description": "Hand-picked farm-fresh premium long-stem red roses. Crisp petals, velvety texture.",
        "price": 799,
        "original_price": 999,
        "pricing_unit": "per 20 stems",
        "stem_count": 20,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 328,
        "b2b_moq": 100,
        "b2b_price_100": 699,
        "b2b_price_500": 649,
        "image": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        "badge": "Best Seller",
        "popularity": 98,
        "is_new": False,
    },
    {
        "id": 2,
        "name": "Elegance Asiatic White Lilies",
        "category": "bouquets",
        "flower_type": "Lilies",
        "color": "White",
        "description": "Pure pristine white lilies with subtle sweet fragrance, accented with eucalyptus.",
        "price": 1199,
        "original_price": 1499,
        "pricing_unit": "per 10 stems",
        "stem_count": 10,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 194,
        "b2b_moq": 50,
        "b2b_price_100": 999,
        "b2b_price_500": 899,
        "image": "https://images.unsplash.com/photo-1533616688419-b7a585564566?auto=format&fit=crop&w=600&q=80",
        "badge": "Premium",
        "popularity": 92,
        "is_new": False,
    },
    {
        "id": 3,
        "name": "Royal Purple Dendrobium Orchids",
        "category": "arrangements",
        "flower_type": "Orchids",
        "color": "Mixed",
        "description": "Exotic Thai purple orchids in a luxury presentation wrap. Long-lasting vase life.",
        "price": 1499,
        "original_price": 1799,
        "pricing_unit": "per 12 stems",
        "stem_count": 12,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 142,
        "b2b_moq": 60,
        "b2b_price_100": 1299,
        "b2b_price_500": 1199,
        "image": "https://images.unsplash.com/photo-1566977776052-6e61e358dd03?auto=format&fit=crop&w=600&q=80",
        "badge": "Exotic",
        "popularity": 89,
        "is_new": True,
    },
    {
        "id": 4,
        "name": "Blush Pink Carnation Bunch",
        "category": "bouquets",
        "flower_type": "Carnations",
        "color": "Pink",
        "description": "Tender ruffled pink carnations symbolizes affection and gratitude. Fresh cut daily.",
        "price": 549,
        "original_price": 699,
        "pricing_unit": "per 15 stems",
        "stem_count": 15,
        "availability": "in_stock",
        "rating": 4.7,
        "reviews": 210,
        "b2b_moq": 100,
        "b2b_price_100": 449,
        "b2b_price_500": 399,
        "image": "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=600&q=80",
        "badge": "Fresh Pick",
        "popularity": 85,
        "is_new": False,
    },
    {
        "id": 5,
        "name": "Fresh Kolkata Yellow Marigolds (Genda)",
        "category": "bulk",
        "flower_type": "Marigold",
        "color": "Yellow",
        "description": "Vibrant traditional golden yellow loose marigolds. Essential for festive & puja decor.",
        "price": 349,
        "original_price": 450,
        "pricing_unit": "per 1 kg net",
        "stem_count": 100,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 512,
        "b2b_moq": 50,
        "b2b_price_100": 269,
        "b2b_price_500": 229,
        "image": "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
        "badge": "Festive Bulk",
        "popularity": 96,
        "is_new": False,
    },
    {
        "id": 6,
        "name": "Pastel Sunshine Rose & Lily Harmony",
        "category": "birthday",
        "flower_type": "Mixed",
        "color": "Mixed",
        "description": "Joyful blend of peach roses, yellow lilies, and white baby's breath in signature box.",
        "price": 1299,
        "original_price": 1599,
        "pricing_unit": "per luxury arrangement",
        "stem_count": 25,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 88,
        "b2b_moq": 30,
        "b2b_price_100": 1099,
        "b2b_price_500": 980,
        "image": "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=600&q=80",
        "badge": "Trending",
        "popularity": 87,
        "is_new": True,
    },
    {
        "id": 7,
        "name": "Bridal Grandeur White Rose Crate",
        "category": "wedding",
        "flower_type": "Roses",
        "color": "White",
        "description": "Graded Grade-A Colombian white roses tailored for mandap and stage installation.",
        "price": 3299,
        "original_price": 3800,
        "pricing_unit": "per crate (100 stems)",
        "stem_count": 100,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 76,
        "b2b_moq": 200,
        "b2b_price_100": 2899,
        "b2b_price_500": 2599,
        "image": "https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=600&q=80",
        "badge": "Wedding Spec",
        "popularity": 91,
        "is_new": False,
    },
    {
        "id": 8,
        "name": "Sunny Yellow Dutch Tulips (Spring Lot)",
        "category": "seasonal",
        "flower_type": "Mixed",
        "color": "Yellow",
        "description": "Air-flown Dutch spring yellow tulips with crisp stems and vibrant cup blooms.",
        "price": 1899,
        "original_price": 2200,
        "pricing_unit": "per 10 stems",
        "stem_count": 10,
        "availability": "pre_order",
        "rating": 4.6,
        "reviews": 43,
        "b2b_moq": 50,
        "b2b_price_100": 1599,
        "b2b_price_500": 1450,
        "image": "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=600&q=80",
        "badge": "Pre-Order",
        "popularity": 78,
        "is_new": True,
    },
    {
        "id": 9,
        "name": "Corporate Wellness Peace Lily Planter",
        "category": "plants",
        "flower_type": "Lilies",
        "color": "White",
        "description": "NASA-recommended air-purifying Spathiphyllum with glossy green leaves in ceramic pot.",
        "price": 849,
        "original_price": 1050,
        "pricing_unit": "per planter",
        "stem_count": 1,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 167,
        "b2b_moq": 25,
        "b2b_price_100": 699,
        "b2b_price_500": 599,
        "image": "https://images.unsplash.com/photo-1593482892290-f54927ae1bf6?auto=format&fit=crop&w=600&q=80",
        "badge": "Eco Pick",
        "popularity": 83,
        "is_new": False,
    },
    {
        "id": 10,
        "name": "Deep Crimson Scarlet Carnations",
        "category": "bulk",
        "flower_type": "Carnations",
        "color": "Red",
        "description": "Hardy long-lasting red carnations, preferred by hotel banquets and event decorators.",
        "price": 499,
        "original_price": 650,
        "pricing_unit": "per 20 stems",
        "stem_count": 20,
        "availability": "in_stock",
        "rating": 4.6,
        "reviews": 98,
        "b2b_moq": 100,
        "b2b_price_100": 399,
        "b2b_price_500": 349,
        "image": "https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=600&q=80",
        "badge": "Hot Deal",
        "popularity": 81,
        "is_new": False,
    },
    {
        "id": 11,
        "name": "Executive Gifting Golden Cymbidium Set",
        "category": "corporate",
        "flower_type": "Orchids",
        "color": "Yellow",
        "description": "Opulent golden yellow Cymbidium orchids presented in an artisan matte-black vase.",
        "price": 2799,
        "original_price": 3400,
        "pricing_unit": "per gift set",
        "stem_count": 8,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 54,
        "b2b_moq": 15,
        "b2b_price_100": 2350,
        "b2b_price_500": 2100,
        "image": "https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=600&q=80",
        "badge": "B2B Choice",
        "popularity": 90,
        "is_new": True,
    },
    {
        "id": 12,
        "name": "Sweet Pink Avalanche Rose Bouquet",
        "category": "birthday",
        "flower_type": "Roses",
        "color": "Pink",
        "description": "Charming soft pink roses with seasonal filler greens and ribbon bow styling.",
        "price": 899,
        "original_price": 1199,
        "pricing_unit": "per 18 stems",
        "stem_count": 18,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 230,
        "b2b_moq": 60,
        "b2b_price_100": 749,
        "b2b_price_500": 680,
        "image": "https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=600&q=80",
        "badge": "Popular",
        "popularity": 94,
        "is_new": False,
    },
    {
        "id": 13,
        "name": "Mandap Special Saffron Orange Marigold",
        "category": "bulk",
        "flower_type": "Marigold",
        "color": "Yellow",
        "description": "Dense, deep saffron orange marigold flower balls. Zero pesticide chemical wash.",
        "price": 389,
        "original_price": 499,
        "pricing_unit": "per 1 kg net",
        "stem_count": 100,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 310,
        "b2b_moq": 100,
        "b2b_price_100": 299,
        "b2b_price_500": 249,
        "image": "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
        "badge": "Wholesale Direct",
        "popularity": 93,
        "is_new": False,
    },
    {
        "id": 14,
        "name": "Stargazer Oriental Pink Lilies",
        "category": "bouquets",
        "flower_type": "Lilies",
        "color": "Pink",
        "description": "Dramatic open star blooms with freckled petals and intoxicating floral notes.",
        "price": 1399,
        "original_price": 1699,
        "pricing_unit": "per 8 stems",
        "stem_count": 8,
        "availability": "in_stock",
        "rating": 4.7,
        "reviews": 84,
        "b2b_moq": 40,
        "b2b_price_100": 1150,
        "b2b_price_500": 1020,
        "image": "https://images.unsplash.com/photo-1533616688419-b7a585564566?auto=format&fit=crop&w=600&q=80",
        "badge": "Fragrant",
        "popularity": 86,
        "is_new": False,
    },
    {
        "id": 15,
        "name": "White & Green European Table Runner",
        "category": "wedding",
        "flower_type": "Mixed",
        "color": "White",
        "description": "Cascading eucalyptus garland studded with white spray roses and baby hydrangeas.",
        "price": 2899,
        "original_price": 3499,
        "pricing_unit": "per 6-foot length",
        "stem_count": 60,
        "availability": "pre_order",
        "rating": 4.9,
        "reviews": 41,
        "b2b_moq": 10,
        "b2b_price_100": 2450,
        "b2b_price_500": 2199,
        "image": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80",
        "badge": "Luxury Decor",
        "popularity": 88,
        "is_new": True,
    },
    {
        "id": 16,
        "name": "Sunny Yellow Gerbera Daisies",
        "category": "all",
        "flower_type": "Mixed",
        "color": "Yellow",
        "description": "Cheerful giant yellow gerberas that instantly brighten up office receptions.",
        "price": 449,
        "original_price": 599,
        "pricing_unit": "per 12 stems",
        "stem_count": 12,
        "availability": "in_stock",
        "rating": 4.6,
        "reviews": 118,
        "b2b_moq": 100,
        "b2b_price_100": 349,
        "b2b_price_500": 299,
        "image": "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
        "badge": "Value Deal",
        "popularity": 79,
        "is_new": False,
    },
    {
        "id": 17,
        "name": "Enchanted Sunset Rainbow Roses",
        "category": "roses",
        "flower_type": "Roses",
        "color": "Mixed",
        "description": "Artisan multi-colored garden roses featuring transitions of amber, pink, and yellow.",
        "price": 1149,
        "original_price": 1399,
        "pricing_unit": "per 15 stems",
        "stem_count": 15,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 162,
        "b2b_moq": 60,
        "b2b_price_100": 949,
        "b2b_price_500": 850,
        "image": "https://images.unsplash.com/photo-1548094891-c4969f4d7421?auto=format&fit=crop&w=600&q=80",
        "badge": "Artisan Pick",
        "popularity": 87,
        "is_new": True,
    },
    {
        "id": 18,
        "name": "Snow White Dutch Chrysanthemums",
        "category": "bulk",
        "flower_type": "Mixed",
        "color": "White",
        "description": "Dense pompom white spray buttons. High hydration tolerance, lasts up to 14 days.",
        "price": 489,
        "original_price": 620,
        "pricing_unit": "per 20 stems",
        "stem_count": 20,
        "availability": "in_stock",
        "rating": 4.7,
        "reviews": 79,
        "b2b_moq": 100,
        "b2b_price_100": 389,
        "b2b_price_500": 329,
        "image": "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
        "badge": "Long Life",
        "popularity": 75,
        "is_new": False,
    },
    {
        "id": 19,
        "name": "Bespoke Grand Wedding Varmala Pair",
        "category": "wedding",
        "flower_type": "Roses",
        "color": "Red",
        "description": "Royal lightweight red rose petal garlands with golden zardozi thread accents.",
        "price": 4499,
        "original_price": 5500,
        "pricing_unit": "per pair (2 varmalas)",
        "stem_count": 200,
        "availability": "pre_order",
        "rating": 5.0,
        "reviews": 63,
        "b2b_moq": 5,
        "b2b_price_100": 3899,
        "b2b_price_500": 3499,
        "image": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        "badge": "Royal Wedding",
        "popularity": 95,
        "is_new": False,
    },
    {
        "id": 20,
        "name": "Ceremonial Jasmine Buds (Mogra Strings)",
        "category": "bulk",
        "flower_type": "Mixed",
        "color": "White",
        "description": "Fragrant morning-harvested Arabian Jasmine mogra strings. Kept chilled in thermocol.",
        "price": 649,
        "original_price": 799,
        "pricing_unit": "per 10 garlands (1 meter each)",
        "stem_count": 100,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 284,
        "b2b_moq": 50,
        "b2b_price_100": 520,
        "b2b_price_500": 460,
        "image": "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
        "badge": "Fragrant Fresh",
        "popularity": 97,
        "is_new": False,
    },
    {
        "id": 21,
        "name": "Fuchsia Velvet Mokara Orchids",
        "category": "arrangements",
        "flower_type": "Orchids",
        "color": "Pink",
        "description": "Rare star-shaped tropical hot-pink mokara orchids, imported under temperature control.",
        "price": 1699,
        "original_price": 2100,
        "pricing_unit": "per 10 stems",
        "stem_count": 10,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 57,
        "b2b_moq": 40,
        "b2b_price_100": 1399,
        "b2b_price_500": 1250,
        "image": "https://images.unsplash.com/photo-1566977776052-6e61e358dd03?auto=format&fit=crop&w=600&q=80",
        "badge": "Rare Bloom",
        "popularity": 84,
        "is_new": True,
    },
    {
        "id": 22,
        "name": "Festive Mixed Pooja Flora Basket",
        "category": "seasonal",
        "flower_type": "Mixed",
        "color": "Mixed",
        "description": "Curated morning pack: Hibiscus, Marigold, Bel Patra, and Lotus bloom for daily worship.",
        "price": 299,
        "original_price": 399,
        "pricing_unit": "per sacred basket",
        "stem_count": 25,
        "availability": "in_stock",
        "rating": 4.9,
        "reviews": 412,
        "b2b_moq": 50,
        "b2b_price_100": 229,
        "b2b_price_500": 189,
        "image": "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=600&q=80",
        "badge": "Daily Ritual",
        "popularity": 96,
        "is_new": False,
    },
    {
        "id": 23,
        "name": "Corporate Event Centerpiece Trio",
        "category": "corporate",
        "flower_type": "Lilies",
        "color": "White",
        "description": "Set of 3 minimalist glass cylinder vases with floating white lilies & submerged orchids.",
        "price": 2499,
        "original_price": 3100,
        "pricing_unit": "per set of 3",
        "stem_count": 15,
        "availability": "in_stock",
        "rating": 4.7,
        "reviews": 38,
        "b2b_moq": 10,
        "b2b_price_100": 2099,
        "b2b_price_500": 1850,
        "image": "https://images.unsplash.com/photo-1533616688419-b7a585564566?auto=format&fit=crop&w=600&q=80",
        "badge": "B2B Pack",
        "popularity": 82,
        "is_new": True,
    },
    {
        "id": 24,
        "name": "Exotic Blue Iris & White Carnation Blend",
        "category": "arrangements",
        "flower_type": "Carnations",
        "color": "Mixed",
        "description": "Striking sapphire blue irises matched with white carnations and sea lavender filler.",
        "price": 1099,
        "original_price": 1350,
        "pricing_unit": "per designer bundle",
        "stem_count": 16,
        "availability": "in_stock",
        "rating": 4.8,
        "reviews": 72,
        "b2b_moq": 40,
        "b2b_price_100": 899,
        "b2b_price_500": 799,
        "image": "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=600&q=80",
        "badge": "Designer Choice",
        "popularity": 86,
        "is_new": False,
    }
]

CATEGORIES = [
    {"id": "all", "name": "All Flowers", "icon": "sparkles"},
    {"id": "roses", "name": "Roses", "icon": "flower"},
    {"id": "bouquets", "name": "Bouquets", "icon": "gift"},
    {"id": "wedding", "name": "Wedding Flowers", "icon": "heart"},
    {"id": "birthday", "name": "Birthday Flowers", "icon": "cake"},
    {"id": "arrangements", "name": "Floral Arrangements", "icon": "palette"},
    {"id": "plants", "name": "Plants", "icon": "leaf"},
    {"id": "corporate", "name": "Corporate Gifting", "icon": "briefcase"},
    {"id": "bulk", "name": "Bulk Flowers", "icon": "boxes"},
    {"id": "seasonal", "name": "Seasonal Flowers", "icon": "sun"},
]

def product_list(request):
    context = {
        'products': PRODUCTS_DATA,
        'products_json': json.dumps(PRODUCTS_DATA),
        'categories': CATEGORIES,
        'total_count': len(PRODUCTS_DATA),
        'shopping_mode': request.GET.get('mode', 'personal'),
    }
    return render(request, 'marketplace/product_list.html', context)

def cart_view(request):
    return render(request, 'marketplace/cart.html', {'categories': CATEGORIES})

def api_products(request):
    return JsonResponse({'status': 'success', 'data': PRODUCTS_DATA})
